name: hydoop
description: "Flutter app for HYROX race data analysis and visualization"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # UI Library
  forui: ^0.15.1
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Local Database & CSV
  sqflite: ^2.4.1
  csv: ^6.0.0
  path: ^1.9.0
  
  # Charts & Visualization
  fl_chart: ^0.69.2
  
  # Navigation
  go_router: ^14.6.2
  
  # Utilities
  shared_preferences: ^2.3.3
  
  # Icons & Assets
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Linting
  flutter_lints: ^5.0.0
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/data/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
